export const MAIL_SELECTORS = {
  appRoot: '[role="main"]',
  searchInput: 'input[aria-label*="Search mail"], input[name="q"]',
  composeButton: '[gh="cm"]',
  composeDialog: '[role="dialog"]:has(input[name="subjectbox"], input[aria-label*="Subject"])',
  anyDialog: '[role="dialog"]',
  threadContainer: '[role="main"] [data-message-id], [role="main"] .adn.ads, [role="main"] .if, [role="main"] .ao9',
  messageBodies: '.a3s.aiL',
  listRows: 'tr[role="row"], [role="main"] table[role="grid"] tr',
  selectedRow: 'tr[role="row"].simply-mail-row-selected',
  toolbarArchive: 'div[aria-label*="Archive"], [data-tooltip*="Archive"]',
  toolbarDelete: 'div[aria-label*="Delete"], [data-tooltip*="Delete"]',
  toolbarMarkReadUnread: 'div[aria-label*="Mark as read"], div[aria-label*="Mark as unread"], [data-tooltip*="Mark as read"], [data-tooltip*="Mark as unread"]',
  backButton: 'div[aria-label="Back to Inbox"], [data-tooltip="Back to Inbox"]',
  replyButton: 'span[role="link"][data-tooltip*="Reply"], [aria-label^="Reply"]',
  sidebar: '[role="navigation"]',
  meetSection: '[aria-label*="meet" i]',
  chatSection: '[aria-label*="chat" i]',
  spacesSection: '[aria-label*="spaces" i]',
  googleAppsButton: '[aria-label*="apps"], a[title*="apps"]',
  selectAllCheckbox: 'div[role="checkbox"][aria-label*="Select"], header div[role="checkbox"]',
  footer: '.aqK, .aeH',
  storageBar: '.md.mj',
  accountElement: 'a[aria-label^="Account:"]',
} as const;
